### PR TITLE
Fix Godot4 syntax errors

### PR DESCRIPTION
**Pull request by fnaith**
Fix Godot4 syntax errors and almost no warning left.
However there are some bugs appear :
- a flashing glitch appears when drawing card into hand store
- mouse hover and drag don't work, maybe the mouse_entered signal isn't triggered

I believe it is very close to migrate this project to Godot 4

### CODE REVIEW

**Comment by BraindeadBZH** [comment]
Hello,
First of all, thank you for your work.
Just did a quick review of the PR. Looks good to me.
Regarding your comment on #21, here is my answer: it always amaze me how well this project did, letting me to believe that a redo for Godot 4, to make it a much more polished tool, is necessary. Unfortunately, I'm quite busy with life right now. I hope I can come back to it at some point.

**Comment by fnaith** [comment]
Understand, but I will still keep migrate this project to Godot 4 (without further polish).

BTW. If you could share the polish plan, maybe somebody can implement it.

Again, thanks for you great tool.

**Comment by BraindeadBZH** [comment]
Thanks.
We can still merge your work if you want.

I don't have big plan yet, but I would probably make it using C++ with a GDExtension, it seems to me that it should be better integrated this way.

**Comment by fnaith** [comment]
This PR is kind of half-baked, I think there is no emergency to merge this PR at this moment.

BTW. I tried c++ extension, and it is very friendly for plan object.

**Pull request closed without merging**
